name: spring-boot-sentry-demo-github-actions
on:
  push:
    branches: [ master ]


jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: 4ad86fb7169441b69688b7d0a0d90f8b2d40262bd4fc45e092305b3f74649dcd
          SENTRY_ORG: ab-zt
          SENTRY_PROJECT: spring-boot
          # SENTRY_URL: https://sentry.io/
        with:
          environment: production
          version: 0.6